### ISSUE TITLE
获取点击遮罩的事件

### ISSUE THREAD

**Issue by ty82885279** [QuintGao/GKCover#2]
你好，大神，我想在点击遮罩的时候，弹窗消失，然后自己做一些事情，怎么监听 点击遮罩的事件 的事件呢？

**Comment by QuintGao** [comment]
可以用下面的方法：
       [GKCover coverFrom:view contentView:imgView style:GKCoverStyleTranslucent showStyle:GKCoverShowStyleTop animStyle:GKCoverAnimStyleTop notClick:NO showBlock:^{
        NSLog(@"遮罩显示了");
    } hideBlock:^{
        NSLog(@"遮罩隐藏了");
        [view removeFromSuperview];
        view = nil;
    }];

在显示和隐藏的block里面做一些事情。
非常感谢支持！

**Comment by QuintGao** [comment]
具体可查看最新Demo
