### ISSUE TITLE
可以在展示的view上添加一个按钮，点击按钮关闭这个弹窗吗？

### ISSUE THREAD

**Issue by ty82885279** [QuintGao/GKCover#4]
大神，你好，我需要在自己展示的view右上角添加一个按钮，点击按钮，实现关闭弹窗。要怎么实现呢?

**Comment by QuintGao** [comment]
你好，可以调用方法[GKCover hideView];来实现点击按钮，关闭弹窗！

**Comment by ty82885279** [comment]
谢谢大神，我使用的是中间弹窗，使用这个后：[GKCover hideView],中间的视图是向屏幕上方滑出去的，能不能直接让它消失？

**Comment by QuintGao** [comment]
可以把动画类型改成GKCoverAnimStyleNone试试
