### ISSUE TITLE
iOS11.2 iPhone 8 Plus 从底部弹出有问题

### ISSUE THREAD

**Issue by py3613778** [QuintGao/GKCover#7]
从底部弹出，底部多余一段距离，并不是从底部直接弹出的

**Comment by QuintGao** [comment]
问题已修复，请更新到最新版本使用。

**Comment by py3613778** [comment]
谢谢亲




| |
潘滢
邮箱：py3613778@163.com
|

签名由 网易邮箱大师 定制

在2018年03月13日 10:01，高坤 写道：

问题已修复，请更新到最新版本使用。
